public with sharing class PaymentTriggerHandler {
    List<sObject> triggerOld = new List<sObject>();
    List<sObject> triggerNew = new List<sObject>();

    public PaymentTriggerHandler() {
    }

    public PaymentTriggerHandler(List<sObject> triggerOld, List<sObject> triggerNew) {
        this.triggerOld = triggerOld;
        this.triggerNew = triggerNew;
    }

    public void beforeInsert() {
        
    }
    public void beforeInsert() {

    }
    public void beforeInsert() {

    }
    public void beforeInsert() {

    }
}